### ISSUE TITLE
MAF Comments

### ISSUE THREAD

**Issue by kmhernan** [NCIP/gdc-docs#191]
Hi :smile: here are my comments

```
Annotated VCF files often have variants reported on multiple transcripts whereas the protected MAF file generated from the VCFs (*protected.maf) only reports the most critically affected one.
```
By definition all MAF files can only handle one transcript and one allele in a record, this makes it sound like this is unique to just the protected MAF.

```
The GDC MAF file format is based on the TCGA Mutation Annotation Format specifications, with some additional columns included and some removed.
```
We didn't remove any columns from the MAF spec as that would break lots of things. However, several columns are very TCGA centric and are deprecated, but still present. Others changed slightly.

```
Variants with Mutation_Status != 'Somatic' or GDC_FILTER = 'GapFiller', 'ContEst', 'multi_allelic', 'nonselectedaliquot', 'BCR_Duplicate' or 'BadSeq' are removed.
```
The exact names of these filters aren't correct, but Zhenyu also had them incorrect in his figure. Like `multi_alleleic` is just `multiallelic`. Probably not a big issue

```
Remaining variants with FILTER != 'panel_of_normals' or PASS are removed.
```
You probably want to clarify that the `FILTER != panel_of_normals` is only relevant for  MuTect2 because we look for our own PON tags in the `GDC_FILTER` column.

```
Remaining variants with SOMATIC != null are included in the Somatic MAF.
```
Actually, to be more specific, it's where `SOMATIC == 1`, but if no known variants are tagged as somatic, it would be null. Also, this does not take into account COSMIC annotation.

```
 "0" is used for regions that do not correspond to a gene
```
The Entrez ID may be zero also because I couldn't map the gene from ENSEMBL to an ENTREZ ID.

```
The rs-IDs from the dbSNP database, null if not found in any database used, or "novel" if there is no dbSNP record, but it is found in other databases
```
It should be `novel` if not found in any database used or `null` if there is not dbSNP record, but it is found in other databases.

```
Updated to reflect validation or verification status and to be in agreement with the VCF VLS field. The values allowed in this field are constrained by the value in the Validation_Status field
```
For the `Mutation_Status` column the part about the VCF isn't relevant here (only TCGA relevant) and we don't really follow those TCGA contraints.

```
BCR aliquot UUID for tumor sample
```
These are actually our GDC aliquot UUIDs

**Comment by wwysoc2** [comment]
Changes have been made. Thank you for your input!
